name = "practise-lean"
version = "0.1.0"
defaultTargets = ["practise-lean"]

[[lean_lib]]
name = "PractiseLean"

[[lean_exe]]
name = "practise-lean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.18.0"
